repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: ^event_planner/api/fixtures
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-symlinks
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: debug-statements
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        args: [--never]
        exclude: ^event_planner/settings

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck

  ###### CI DISABLED ######

  # The hooks below are disabled on the CI as they are redundant with the existing CI checks.
  # They're still useful for local development.
  #

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint

  - repo: https://github.com/python-poetry/poetry
    rev: "1.6.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--check]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: "24.1.1"
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: mypy
        name: type checking - mypy
        language: system
        entry: poetry run mypy -p event_planner
        pass_filenames: false
