target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
  # pydocstyle
  "D100",      # Missing docstring in public module
  "D101",      # Missing docstring in public class
  "D104",      # Missing docstring in public package
  "D106",      # Missing docstring in public nested class
  "D203",      # 1 blank line required before class docstring
               # Mutually exclusive with D211 (blank-line-before-class)
  "D212",      # Multi-line docstring summary should start at the first line
               # Mutually exclusive with D213 (multi-line-summary-second-line)
  "D407",      # Missing dashed underline after section
               # We're not using numpy docstring style

  # flake8-annotations
  "ANN101",    # missing-type-self
  "ANN401",    # any-type

  # flake8-tidy-imports
  "TID252",    # relative-imports

  # flake8-pytest-style
  "PT",

  # ruff-specific rules
  "RUF012",    # Mutable class attributes should be annotated with typing.ClassVar
]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?)|args|kwargs)$"

[lint.per-file-ignores]
# These directories are not packages, so we don't need __init__.py
"scripts/*" = ["INP001"]
"*/settings/environment/*" = ["INP001"]

# On tests disable
"*/*/tests/*" = [
  "D205",  # 1 blank line required between summary line and description,
           # so we can have our own docstring format
]

# On migrations disable
"*/*/migrations/*" = [
  "E501",   # Line too long
  "RUF012", # Mutable class attributes should be annotated with `typing.ClassVar`
]

[lint.pylint]
max-args = 5

[lint.flake8-annotations]
allow-star-arg-any = true
