name: Release Production

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump-version.outputs.new-version }}
      new-sha: ${{ steps.bump-version.outputs.new-sha }}
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: Flawless-Workflow/flawless-github-actions/setup-python@main

      - uses: Flawless-Workflow/flawless-github-actions/bump-version@main
        id: bump-version

  build-and-push:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: Flawless-Workflow/flawless-github-actions/publish-docker@main
        with:
          login-server: ${{ secrets.PRODUCTION_REGISTRY_URI }}
          username: ${{ secrets.PRODUCTION_REGISTRY_USERNAME }}
          password: ${{ secrets.PRODUCTION_REGISTRY_PASSWORD }}
          tags: |
            latest
            ${{ needs.bump-version.outputs.new-version }}
          build-args: |
            ENV_TYPE=production
