name: Update Dependencies

on:
  schedule:
    - cron: "0 0 * * 0" # Midnight on Sunday
  workflow_dispatch:

jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: Flawless-Workflow/flawless-github-actions/update-poetry@main
      - uses: Flawless-Workflow/flawless-github-actions/upload-patch@main
        with:
          patch-group: poetry-lock

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: Flawless-Workflow/flawless-github-actions/update-python@main
      - uses: Flawless-Workflow/flawless-github-actions/upload-patch@main
        with:
          patch-group: poetry-lock

  python-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: Flawless-Workflow/flawless-github-actions/setup-python@main

      - name: Update dependencies
        run: |
          pipx inject poetry poetry-plugin-up
          poetry up --latest
      - uses: Flawless-Workflow/flawless-github-actions/upload-patch@main
        with:
          patch-group: poetry-lock

  pre-commit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: Flawless-Workflow/flawless-github-actions/update-pre-commit@main
      - uses: Flawless-Workflow/flawless-github-actions/upload-patch@main

  github-actions-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Run GitHub Actions Version Updater
        continue-on-error: true
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          skip_pull_request: true

      - uses: Flawless-Workflow/flawless-github-actions/upload-patch@main

  poetry-lock:
    needs:
      - poetry
      - python
      - python-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: Flawless-Workflow/flawless-github-actions/apply-patch@main
        id: apply-patch
        with:
          patch-group: poetry-lock

      - uses: Flawless-Workflow/flawless-github-actions/setup-python@main
        if: ${{ steps.apply-patch.outputs.changes-found == 'true' }}

      - name: Regenerate poetry.lock
        run: |
          rm poetry.lock
          poetry lock --no-update
        if: ${{ steps.apply-patch.outputs.changes-found == 'true' }}

      - uses: Flawless-Workflow/flawless-github-actions/upload-patch@main
        if: ${{ steps.apply-patch.outputs.changes-found == 'true' }}

  docker-dependencies:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    strategy:
      matrix:
        package:
          - curl
          - wget
          - build-essential
    steps:
      - uses: Flawless-Workflow/flawless-github-actions/get-apt-version@main
        id: get-apt-version
        with:
          package: ${{ matrix.package }}

      - uses: actions/checkout@v4.1.1
      - run: git config --global --add safe.directory '*'

      - name: Update Dockerfile with new dependency version
        run: |
          package="${{ matrix.package }}"
          version="${{ steps.get-apt-version.outputs.version }}"
          sed -i -E "s/($package=)[^ \\]*([ \]|$)/\\1$version\\2/" Dockerfile
      - uses: Flawless-Workflow/flawless-github-actions/upload-patch@main

  commit-push:
    needs:
      - poetry-lock
      - pre-commit-dependencies
      - github-actions-dependencies
      - docker-dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: Flawless-Workflow/flawless-github-actions/apply-patch@main
        id: apply-patch

      - uses: Flawless-Workflow/flawless-github-actions/pre-commit@main
        if: ${{ steps.apply-patch.outputs.changes-found == 'true' }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5.0.2
        if: ${{ steps.apply-patch.outputs.changes-found == 'true' }}
        with:
          token: ${{ secrets.PAT_COMMIT_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            This PR updates the dependencies of this repository.
            Please review the changes and merge this PR if it looks good.
          branch: update-dependencies
          branch-suffix: timestamp
          delete-branch: true
          labels: dependencies
          reviewers: "XF-FW"

  cleanup-artifacts:
    needs: commit-push
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Delete all artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: default*
